# Generated by Django 3.2.4 on 2021-06-16 11:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booster',
            fields=[
                ('code', models.TextField(primary_key=True, serialize=False, unique=True)),
                ('launches_count', models.IntegerField()),
                ('expended', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Payload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='RocketModel',
            fields=[
                ('model', models.TextField(primary_key=True, serialize=False, unique=True)),
                ('name', models.TextField()),
                ('reusable', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='LaunchPlatform',
            fields=[
                ('code', models.TextField(primary_key=True, serialize=False, unique=True)),
                ('location', models.TextField()),
                ('available_models', models.ManyToManyField(to='api.RocketModel')),
            ],
        ),
        migrations.CreateModel(
            name='Launch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateField(auto_now_add=True)),
                ('booster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.booster')),
                ('launch_platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.launchplatform')),
                ('payload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.payload')),
            ],
        ),
        migrations.AddField(
            model_name='booster',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.rocketmodel'),
        ),
    ]
