# Generated by Django 3.2.4 on 2021-06-16 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210616_1327'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('token', models.TextField(primary_key=True, serialize=False)),
            ],
        ),
    ]
