# Generated by Django 3.2.4 on 2021-06-16 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210616_1840'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='launchplatform',
            name='available_models',
        ),
    ]
