# Generated by Django 3.2.4 on 2021-06-16 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210616_1940'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booster',
            options={'ordering': ['date_created']},
        ),
        migrations.AlterModelOptions(
            name='launch',
            options={'ordering': ['date_created']},
        ),
        migrations.AlterModelOptions(
            name='launchplatform',
            options={'ordering': ['date_created']},
        ),
        migrations.AlterModelOptions(
            name='payload',
            options={'ordering': ['date_created']},
        ),
        migrations.AlterModelOptions(
            name='rocketmodel',
            options={'ordering': ['date_created']},
        ),
    ]
