# Generated by Django 3.2.4 on 2021-06-16 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210616_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='payload',
            name='delivered',
            field=models.BooleanField(default=False),
        ),
    ]
