# Generated by Django 3.2.4 on 2021-06-16 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_payload_delivered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='launch',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
