# Generated by Django 3.2.4 on 2021-06-17 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_launch_start_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Decomission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.rocketmodel')),
            ],
        ),
    ]
